/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.car;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;

import androidx.localbroadcastmanager.content.LocalBroadcastManager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import java.util.HashMap;


@Kroll.module(name = "TiCar", id = "ti.car")
public class TiCarModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiCarModule";
    private static final boolean DBG = TiConfig.LOGD;
    public static HashMap listData;
    private final IntentFilter mIntentFilter;

    // You can define constants with @Kroll.constant, for example:
    // @Kroll.constant public static final String EXTERNAL_NAME = value;

    public TiCarModule() {
        super();
        mIntentFilter = new IntentFilter();
        mIntentFilter.addAction("click");
        LocalBroadcastReceiver lbr = new LocalBroadcastReceiver();
        LocalBroadcastManager.getInstance(TiApplication.getAppRootOrCurrentActivity()).registerReceiver(lbr, mIntentFilter);
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    // Methods
    @Kroll.method
    public void createListTemplate(HashMap data) {
        listData = data;
        listData.put("type", TiConvert.toString(data.get("type"), "list"));
    }

    @Kroll.method
    public void createMessageTemplate(KrollDict data) {
        listData = data;
        listData.put("type", "message");
    }

    @Kroll.method
    public void createToast(String message) {
        TiCarScreen.createToast(message);
    }

    public class LocalBroadcastReceiver extends BroadcastReceiver {
        @Override
        public void onReceive(Context context, Intent intent) {
            KrollDict kd = new KrollDict();
            String action = intent.getAction();
            if (action.equals("click")) {
                kd.put("index", intent.getIntExtra("index", -1));
                fireEvent("click", kd);
            }
        }
    }
}
