/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.car;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import java.util.HashMap;


@Kroll.module(name = "TiCar", id = "ti.car")
public class TiCarModule extends KrollModule {

    private static TiCarModule instance;
    public static HashMap listData;

    // You can define constants with @Kroll.constant, for example:
    // @Kroll.constant public static final String EXTERNAL_NAME = value;

    public TiCarModule() {
        super();
        instance = this;
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    public static void fireClickEvent(int sectionIndex, int itemIndex, String text) {
        TiCarModule module = instance;
        if (module != null) {
            KrollDict kd = new KrollDict();
            kd.put("index", itemIndex);
            kd.put("sectionIndex", sectionIndex);
            kd.put("text", text);
            module.fireEvent("click", kd);
        }
    }

    // Methods
    @Kroll.method
    public void createListTemplate(HashMap data) {
        listData = data;
        listData.put("type", TiConvert.toString(data.get("type"), "list"));
        TiCarScreen.updateScreen();
    }

    @Kroll.method
    public void createMessageTemplate(KrollDict data) {
        listData = data;
        listData.put("type", "message");
        TiCarScreen.updateScreen();
    }

    @Kroll.method
    public void createToast(String message) {
        TiCarScreen.createToast(message);
    }
}
